### ISSUE TITLE
Proper packaging

### ISSUE THREAD

**Issue by iankorf** [KorfLab/grimoire#15]
At some point, we need to organize things into a proper package. This may mean moving the library modules into a grimoire directory and the scripts into a bin directory. Still trying to figure out the pythonic way to do this.

**Comment by JackSSK** [comment]
Could we have __init__.py  having nothing in it?

**Comment by iankorf** [comment]
Yeah, that's okay

**Comment by JackSSK** [comment]
I have tried to test things through tests.py
Some are OK: 
test_DNA (__main__.TestSequence) ... ok
test_generate_kmers (__main__.TestSequence) ... ok
test_revcomp_str (__main__.TestSequence) ... ok
test_translate_str (__main__.TestSequence) ... ok
test_log (__main__.TestToolbox) ... ok
test_sumlog (__main__.TestToolbox) ... ok

All others are ERROR:
test_Genome (__main__.TestGenome) ... ERROR
test_Decode_StochasticViterbi (__main__.TestHMM) ... ERROR
test_Decode_StochasticViterbi_logspace (__main__.TestHMM) ... ERROR
test_Decode_Viterbi (__main__.TestHMM) ... ERROR
test_Decode_Viterbi_logspace (__main__.TestHMM) ... ERROR
test_HMM_emit (__main__.TestHMM) ... ERROR
test_FASTA_file (__main__.TestToolbox) ... ERROR
test_FASTA_stream (__main__.TestToolbox) ... ERROR
test_GFF_file (__main__.TestToolbox) ... ERROR
test_GFF_stream (__main__.TestToolbox) ... ERROR

I think these errors are mainly resulted by changes in directory.
For example, in def test_Genome line 71-72, I believe the path should be described as:
gen = genome.Genome(
			fasta='../../data/A.thaliana.1percent.fasta',
			gff3='../../data/A.thaliana.1percent.gff3',
			chr_map=map)
instead of:
gen = genome.Genome(
			fasta='data/A.thaliana.1percent.fasta',
			gff3='data/A.thaliana.1percent.gff3',
			chr_map=map)

However, there are also other errors after I tried to fix the path problems, e.g.:
TypeError: 'NoneType' object is not subscriptable

Should I try to fix them up?

**Comment by iankorf** [comment]
I've been woking on the new directory structure and internal import path structure. Some things are broken but will be fixed soon.

**Comment by iankorf** [comment]
Also, the way to use the test programs is from setup in the grimoire root

	python3 setup.py test

**Comment by iankorf** [comment]
I think things are packaged correctly and ready for distribution for PyPI. Need some more unit tests and other things, which I'll enumerate in another issue.
